// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tryps-variants/NightFlight.tsx": () => import("../components/mockups/tryps-variants/NightFlight.tsx"),
  "./components/mockups/tryps-variants/Sunshine.tsx": () => import("../components/mockups/tryps-variants/Sunshine.tsx")
};
