// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/blog/HowToPlanGroupTrip.tsx": () => import("../components/mockups/blog/HowToPlanGroupTrip.tsx"),
  "./components/mockups/tryps-variants/Coastal.tsx": () => import("../components/mockups/tryps-variants/Coastal.tsx"),
  "./components/mockups/tryps-variants/Crimson.tsx": () => import("../components/mockups/tryps-variants/Crimson.tsx"),
  "./components/mockups/tryps-variants/Editorial.tsx": () => import("../components/mockups/tryps-variants/Editorial.tsx"),
  "./components/mockups/tryps-variants/Golden.tsx": () => import("../components/mockups/tryps-variants/Golden.tsx"),
  "./components/mockups/tryps-variants/Gradient.tsx": () => import("../components/mockups/tryps-variants/Gradient.tsx"),
  "./components/mockups/tryps-variants/NightFlight.tsx": () => import("../components/mockups/tryps-variants/NightFlight.tsx"),
  "./components/mockups/tryps-variants/Punchy.tsx": () => import("../components/mockups/tryps-variants/Punchy.tsx"),
  "./components/mockups/tryps-variants/Sunshine.tsx": () => import("../components/mockups/tryps-variants/Sunshine.tsx")
};
